# Generated by Django 5.1.4 on 2024-12-25 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_alter_course_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='start_time',
        ),
    ]
