# Generated by Django 5.1.4 on 2024-12-25 15:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_remove_course_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
