# Generated by Django 5.1.4 on 2024-12-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_alter_course_start_time_alter_course_time_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='time_duration',
            field=models.DurationField(help_text='duration of exam', null=True),
        ),
    ]
