# Generated by Django 5.1.4 on 2024-12-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_examattempt_delete_countdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='time_duration',
            field=models.IntegerField(),
        ),
    ]
