# Generated by Django 5.1.4 on 2024-12-30 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_alter_course_time_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='start_time',
        ),
    ]
