# Generated by Django 5.1.4 on 2024-12-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_remove_course_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='time_duration',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
