# Generated by Django 5.1.4 on 2025-01-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0017_alter_result_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='exam_password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
