# Generated by Django 5.1.4 on 2025-01-24 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_customuser_options_alter_customuser_sex'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_manage_students', 'Can manage students')], 'verbose_name': 'Student', 'verbose_name_plural': 'students'},
        ),
    ]
